#Use mini-message style color formatting
#https://webui.adventure.kyori.net/
#Placeholders: <playername> | <sleeping> | <needed> | <worldname>
player-sleep-message: "<grey><playername> has fallen asleep. <sleeping> out of <needed> required players in <worldname> are sleeping."
#Placeholders: <worldname>
night-skip-message: "<grey>Enough players have slept! Skipping through the night in <worldname>."