name: SleepMessages
version: '${project.version}'
main: adhdmc.sleepmessages.SleepMessages
api-version: 1.19
description: Puts a message in chat when someone sleeps
commands:
  sleepmessages:
    description: Command for SleepMessages
    permission: sleepmessages.commands
permissions:
  sleepmessages.commands:
    description: allows user to reload the SleepMessages config file